// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: protocol/customer_service.proto

/*
Package protocol is a generated protocol buffer package.

It is generated from these files:
	protocol/customer_service.proto

It has these top-level messages:
	ResponseType
	RequestType
	Person
*/
package protocol

import fmt "fmt"
import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import math "math"
import _ "github.com/mwitkow/go-proto-validators"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *ResponseType) Validate() error {
	return nil
}
func (this *RequestType) Validate() error {
	return nil
}
func (this *Person) Validate() error {
	if !(this.Age > 0) {
		return github_com_mwitkow_go_proto_validators.FieldError("Age", fmt.Errorf(`value '%v' must be greater than '0'`, this.Age))
	}
	if !(this.Age < 100) {
		return github_com_mwitkow_go_proto_validators.FieldError("Age", fmt.Errorf(`value '%v' must be less than '100'`, this.Age))
	}
	return nil
}
